---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[CVE-2014-3566-poodle::default]
    attributes:
  - name: install_nginx_443_broken
    run_list:
      - recipe[nginx_ssl_broken]
      - recipe[nginx_ssl_broken::turn_on_ssl]
      - recipe[CVE-2014-3566-poodle::default]
    attributes:
  - name: install_nginx_443_fixed
    run_list:
      - recipe[nginx_ssl_fixed]
      - recipe[nginx_ssl_fixed::turn_on_ssl]
      - recipe[CVE-2014-3566-poodle::default]
    attributes:
